# Generated by Django 3.2.7 on 2021-10-04 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date', models.DateField(verbose_name='Invoice date')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_accountinvoice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('modified', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_accountinvoice_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_accountinvoiceline_created_by', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.accountinvoice', verbose_name='Invoice')),
                ('modified', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_accountinvoiceline_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
