# Generated by Django 3.2.7 on 2021-10-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinvoiceline',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
